using Life_Admin_Autopilot.BLL.Features.Tasks;
using Life_Admin_Autopilot.BLL.Kernel.Json;
using Life_Admin_Autopilot.DAL.Features.Digest;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Driver;

namespace Life_Admin_Autopilot.BLL.Features.Digest;

/// <summary>
/// Port of <c>buildDailyDigest</c> from <c>server/src/modules/tasks/dailyDigest.ts</c>
/// — the dashboard's cached, every-visit read.
///
/// <para><b>Why there is a cache at all.</b> The counts are cheap and deterministic;
/// the prose is neither. This endpoint loads on every dashboard visit, so in the
/// Node original a model call per request was never affordable. Hence the row in
/// <c>dailydigests</c>: the state is reduced to a cheap fingerprint, and a request
/// whose fingerprint still matches is served verbatim from the stored payload.</para>
///
/// <para><b>The cache is real, and that is observable.</b> <c>generatedAt</c> is the
/// instant the digest was COMPUTED, not the instant of the request, so three
/// successive calls return the identical timestamp and it drifts steadily into the
/// past. A "cache" that recomputed per request would be caught by that field alone.
/// </para>
///
/// <para><b>NOT gated on AI.</b> Unlike every other generative surface, this returns
/// a complete 200 with no model configured: the counts need none, and the headline
/// is code-generated by <see cref="NeutralHeadline"/>. Only auth and the database
/// can fail this route.</para>
///
/// <para><b>NOT IMPLEMENTED HERE: the background prose refinement.</b> Node follows
/// every cache miss with an unawaited <c>refineProse</c> that asks Gemini for a
/// better headline and theme labels and patches the stored row afterwards, guarded
/// by the <c>sourceHash</c> it was generated from. That is <c>dailyDigestProse.ts</c>
/// and it belongs to the deferred Langflow phase. Its absence is exactly the
/// no-<c>GEMINI_API_KEY</c> reference behaviour this port targets: with no key the
/// Node writer returns nothing, patches nothing, and the computed headline is what
/// every read sees. The one piece of that file ported here is
/// <see cref="DigestThemes.KeepReal"/>, which is not AI code — see the note there.
/// </para>
/// </summary>
public sealed class DailyDigestService
{
    private readonly DailyDigestRepository _digests;
    private readonly DailyDigestSourceReader _source;
    private readonly DailyDigestComputer _computer;
    private readonly UserLocaleReader _locales;
    private readonly ILogger<DailyDigestService> _logger;

    public DailyDigestService(
        DailyDigestRepository digests,
        DailyDigestSourceReader source,
        DailyDigestComputer computer,
        UserLocaleReader locales,
        ILogger<DailyDigestService> logger)
    {
        _digests = digests;
        _source = source;
        _computer = computer;
        _locales = locales;
        _logger = logger;
    }

    public async Task<DailyDigestPayloadDocument> BuildAsync(
        ObjectId userId,
        string? requestedTimezone,
        DateTime? at = null,
        CancellationToken cancellationToken = default)
    {
        var now = DateTime.SpecifyKind(at ?? DateTime.UtcNow, DateTimeKind.Utc);
        var timezone = DigestClock.SafeTimezone(requestedTimezone, _logger);
        var localDate = DigestClock.LocalDateKey(now, timezone);

        var locale = await _locales.ReadAsync(userId, cancellationToken).ConfigureAwait(false);

        var sourceTask = _source.ReadAsync(userId, localDate, now, locale, cancellationToken);
        var cachedTask = _digests.FindAsync(userId, localDate, cancellationToken);

        await Task.WhenAll(sourceTask, cachedTask).ConfigureAwait(false);

        var source = await sourceTask.ConfigureAwait(false);
        var cached = await cachedTask.ConfigureAwait(false);

        if (cached is not null && string.Equals(cached.SourceHash, source.Hash, StringComparison.Ordinal))
        {
            return FromCache(cached.Payload);
        }

        var computed = await _computer
            .ComputeAsync(userId, now, timezone, source, cancellationToken)
            .ConfigureAwait(false);

        // Themes carry over from the last successful build, re-validated against
        // today's matters, so they are stale only in WORDING. The headline is never
        // carried: a sentence about yesterday presented as today is a lie, whereas a
        // plain count is merely plain.
        //
        // Carried forward only WITHIN ONE LANGUAGE. Wording from the language the
        // user just left is not stale — it is wrong, and it would sit directly under
        // a headline that already switched. A row with no stored locale (written
        // before the field existed) never matches, so it never carries either.
        var carried = string.Equals(cached?.Locale, locale, StringComparison.Ordinal)
            ? cached!.Payload.Themes
            : new List<DailyDigestThemeDocument>();

        var payload = new DailyDigestPayloadDocument
        {
            LocalDate = localDate,
            GeneratedAt = JsIsoDateTimeConverter.ToIso(now),
            Headline = NeutralHeadline.For(computed.Counts),
            Counts = computed.Counts,
            EstimatedMinutesToday = computed.EstimatedMinutesToday,
            Themes = DigestThemes.KeepReal(carried, computed.PoolIds),
            BusiestDay = computed.BusiestDay,
            Duplicates = computed.Duplicates,
        };

        try
        {
            await _digests
                .UpsertAsync(userId, localDate, source.Hash, locale, now, payload, cancellationToken)
                .ConfigureAwait(false);
        }
        catch (MongoException ex)
        {
            // A concurrent dashboard load inserted the same row first (unique index).
            // The payload in hand is still correct — serving it beats failing the
            // dashboard's headline read on a cache write.
            _logger.LogWarning(ex, "daily-digest:cache-write-failed localDate={LocalDate}", localDate);
        }

        return payload;
    }

    /// <summary>
    /// Rebuild the response from a stored row. EXPLICIT rather than returned by
    /// reference, so a field added to the schema without a migration surfaces here
    /// instead of silently missing from the response — and so a caller cannot mutate
    /// the cached instance.
    /// </summary>
    private static DailyDigestPayloadDocument FromCache(DailyDigestPayloadDocument payload) => new()
    {
        LocalDate = payload.LocalDate,
        GeneratedAt = payload.GeneratedAt,
        Headline = payload.Headline,
        Counts = new DailyDigestCountsDocument
        {
            DueToday = payload.Counts.DueToday,
            CompletedToday = payload.Counts.CompletedToday,
            OpenTotal = payload.Counts.OpenTotal,
            Slipping = payload.Counts.Slipping,
            NeedsInput = payload.Counts.NeedsInput,
            ScansAwaitingReview = payload.Counts.ScansAwaitingReview,
        },
        EstimatedMinutesToday = new DailyDigestEstimateDocument
        {
            Min = payload.EstimatedMinutesToday.Min,
            Max = payload.EstimatedMinutesToday.Max,
        },
        Themes = payload.Themes
            .Select(t => new DailyDigestThemeDocument
            {
                Label = t.Label,
                Count = t.Count,
                TaskIds = t.TaskIds.ToList(),
            })
            .ToList(),
        BusiestDay = payload.BusiestDay is null
            ? null
            : new DailyDigestBusiestDayDocument
            {
                Date = payload.BusiestDay.Date,
                Count = payload.BusiestDay.Count,
            },
        Duplicates = payload.Duplicates
            .Select(d => new DailyDigestDuplicateDocument
            {
                Title = d.Title,
                Count = d.Count,
                TaskIds = d.TaskIds.ToList(),
            })
            .ToList(),
    };
}
