using Life_Admin_Autopilot.BLL.Features.Tasks;
using Life_Admin_Autopilot.BLL.Kernel.Json;
using Life_Admin_Autopilot.DAL.Features.Digest;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using MongoDB.Driver;

namespace Life_Admin_Autopilot.BLL.Features.Digest;

/// <summary>
/// A built digest plus the one thing about it that is not in the payload: whether a
/// better headline is on its way.
/// </summary>
/// <param name="ProsePending">
/// True only when a model call for this day is genuinely in flight. The dashboard
/// refetches while it is true, so an optimistic value here is a client that polls
/// forever.
/// </param>
public sealed record DailyDigestResult(DailyDigestPayloadDocument Payload, bool ProsePending);

/// <summary>
/// Port of <c>buildDailyDigest</c> from <c>server/src/modules/tasks/dailyDigest.ts</c>
/// — the dashboard's cached, every-visit read.
///
/// <para><b>Why there is a cache at all.</b> The counts are cheap and deterministic;
/// the prose is neither. This endpoint loads on every dashboard visit, so in the
/// Node original a model call per request was never affordable. Hence the row in
/// <c>dailydigests</c>: the state is reduced to a cheap fingerprint, and a request
/// whose fingerprint still matches is served verbatim from the stored payload.</para>
///
/// <para><b>The cache is real, and that is observable.</b> <c>generatedAt</c> is the
/// instant the digest was COMPUTED, not the instant of the request, so three
/// successive calls return the identical timestamp and it drifts steadily into the
/// past. A "cache" that recomputed per request would be caught by that field alone.
/// </para>
///
/// <para><b>NOT gated on AI.</b> Unlike every other generative surface, this returns
/// a complete 200 with no model configured: the counts need none, and the headline
/// is code-generated by <see cref="NeutralHeadline"/>. Only auth and the database
/// can fail this route.</para>
///
/// <para><b>The prose refinement is queued, never awaited.</b> A cache miss drops a
/// job on <see cref="DigestProseQueue"/> and answers immediately with
/// <see cref="NeutralHeadline"/>'s sentence; <c>DigestProseWorker</c> asks the model
/// for a better one and patches the row under the <c>sourceHash</c> it was generated
/// from. Awaiting it here would put a language model on the dashboard's critical
/// path for numbers that are already finished, and the wait would land on exactly
/// the visits that matter — a miss means the user just changed something, so the
/// moment they act would be the moment the home screen went quiet.
/// </para>
///
/// <para>
/// With no model configured nothing is queued, <see cref="DailyDigestResult.ProsePending"/>
/// is false, and this behaves exactly as the no-<c>GEMINI_API_KEY</c> reference does:
/// the computed headline is what every read sees.
/// </para>
/// </summary>
public sealed class DailyDigestService
{
    private readonly DailyDigestRepository _digests;
    private readonly DailyDigestSourceReader _source;
    private readonly DailyDigestComputer _computer;
    private readonly UserLocaleReader _locales;
    private readonly DigestProseQueue _prose;
    private readonly DigestProseWriter _writer;
    private readonly ILogger<DailyDigestService> _logger;

    public DailyDigestService(
        DailyDigestRepository digests,
        DailyDigestSourceReader source,
        DailyDigestComputer computer,
        UserLocaleReader locales,
        DigestProseQueue prose,
        DigestProseWriter writer,
        ILogger<DailyDigestService> logger)
    {
        _digests = digests;
        _source = source;
        _computer = computer;
        _locales = locales;
        _prose = prose;
        _writer = writer;
        _logger = logger;
    }

    public async Task<DailyDigestResult> BuildAsync(
        ObjectId userId,
        string? requestedTimezone,
        DateTime? at = null,
        CancellationToken cancellationToken = default)
    {
        var now = DateTime.SpecifyKind(at ?? DateTime.UtcNow, DateTimeKind.Utc);
        var timezone = DigestClock.SafeTimezone(requestedTimezone, _logger);
        var localDate = DigestClock.LocalDateKey(now, timezone);

        var locale = await _locales.ReadAsync(userId, cancellationToken).ConfigureAwait(false);

        var sourceTask = _source.ReadAsync(userId, localDate, now, locale, cancellationToken);
        var cachedTask = _digests.FindAsync(userId, localDate, cancellationToken);

        await Task.WhenAll(sourceTask, cachedTask).ConfigureAwait(false);

        var source = await sourceTask.ConfigureAwait(false);
        var cached = await cachedTask.ConfigureAwait(false);

        if (cached is not null && string.Equals(cached.SourceHash, source.Hash, StringComparison.Ordinal))
        {
            // A hit is also how the dashboard COLLECTS the model's sentence: it
            // refetches while a write is in flight, and the row it reads back is the
            // patched one. So the pending flag has to be answered here too, not only
            // on the miss that started the job.
            //
            // And a hit is where the sentence usually has to be ASKED FOR, which is
            // less obvious. Almost every read is a hit — the miss only happens on the
            // first load after the user changes something — so queueing on the miss
            // alone leaves any row that predates a reachable model stuck with its
            // computed headline until the facts move. See TryQueueProseForCachedAsync
            // for why that cannot simply queue on every hit.
            var pending = _prose.IsPending(userId, localDate) ||
                await TryQueueProseForCachedAsync(cached, userId, localDate, now, timezone, locale, cancellationToken)
                    .ConfigureAwait(false);

            return new DailyDigestResult(FromCache(cached.Payload), pending);
        }

        var computed = await _computer
            .ComputeAsync(userId, now, timezone, source, cancellationToken)
            .ConfigureAwait(false);

        // Themes carry over from the last successful build, re-validated against
        // today's matters, so they are stale only in WORDING. The headline is never
        // carried: a sentence about yesterday presented as today is a lie, whereas a
        // plain count is merely plain.
        //
        // Carried forward only WITHIN ONE LANGUAGE. Wording from the language the
        // user just left is not stale — it is wrong, and it would sit directly under
        // a headline that already switched. A row with no stored locale (written
        // before the field existed) never matches, so it never carries either.
        var carried = string.Equals(cached?.Locale, locale, StringComparison.Ordinal)
            ? cached!.Payload.Themes
            : new List<DailyDigestThemeDocument>();

        var payload = new DailyDigestPayloadDocument
        {
            LocalDate = localDate,
            GeneratedAt = JsIsoDateTimeConverter.ToIso(now),
            Headline = NeutralHeadline.For(computed.Counts),
            Counts = computed.Counts,
            EstimatedMinutesToday = computed.EstimatedMinutesToday,
            Themes = DigestThemes.KeepReal(carried, computed.PoolIds),
            BusiestDay = computed.BusiestDay,
            Duplicates = computed.Duplicates,
        };

        try
        {
            await _digests
                .UpsertAsync(userId, localDate, source.Hash, locale, now, payload, cancellationToken)
                .ConfigureAwait(false);
        }
        catch (MongoException ex)
        {
            // A concurrent dashboard load inserted the same row first (unique index).
            // The payload in hand is still correct — serving it beats failing the
            // dashboard's headline read on a cache write.
            _logger.LogWarning(ex, "daily-digest:cache-write-failed localDate={LocalDate}", localDate);
        }

        // Queued AFTER the write, so the row the worker patches is already there. A
        // job that beat the upsert would find nothing to match and drop its sentence
        // for no reason.
        var prosePending = TryQueueProse(userId, localDate, source.Hash, locale, now, computed.Pool);

        return new DailyDigestResult(payload, prosePending);
    }

    /// <summary>
    /// Ask for a better sentence, if there is anything to say it about and anyone to
    /// ask.
    ///
    /// <para>
    /// The return value is a PROMISE TO THE CLIENT, not a hope: the dashboard polls
    /// while it is true. So it is false whenever no sentence is actually coming — no
    /// model configured, nothing due to describe, or a full queue — rather than
    /// optimistic. A client left polling for a write that will never happen is worse
    /// than one that simply shows the count.
    /// </para>
    /// </summary>
    /// <summary>
    /// Ask for a sentence about a day whose numbers are already cached and correct.
    ///
    /// <para>
    /// <b>Gated on <see cref="DailyDigestDocument.ProseAttemptedHash"/>, and it has to
    /// be.</b> A hit cannot decide from the headline alone whether to ask — a model
    /// that answered nothing leaves the computed sentence in place, which is
    /// indistinguishable from never having asked. Queueing on every such hit would
    /// turn a day the model is unreachable into one request per dashboard load, and
    /// the client polls every two seconds while a job is pending, so that is a loop
    /// rather than a nuisance. The stamp is the one durable record of "asked".
    /// </para>
    ///
    /// <para>
    /// The pool is read on its own rather than by rebuilding: the counts in the row
    /// are current, and a rebuild would rewrite <c>generatedAt</c> for no reason. It
    /// costs one find, and only until this fingerprint has had its attempt.
    /// </para>
    /// </summary>
    private async Task<bool> TryQueueProseForCachedAsync(
        DailyDigestDocument cached,
        ObjectId userId,
        string localDate,
        DateTime now,
        string? timezone,
        string locale,
        CancellationToken cancellationToken)
    {
        if (!_writer.IsConfigured ||
            string.Equals(cached.ProseAttemptedHash, cached.SourceHash, StringComparison.Ordinal))
        {
            return false;
        }

        var pool = await _computer
            .ReadPoolAsync(userId, now, timezone, cancellationToken)
            .ConfigureAwait(false);

        return TryQueueProse(userId, localDate, cached.SourceHash, locale, now, pool);
    }

    private bool TryQueueProse(
        ObjectId userId,
        string localDate,
        string sourceHash,
        string locale,
        DateTime now,
        IReadOnlyList<DigestPoolMatter> pool)
    {
        if (!_writer.IsConfigured || pool.Count == 0)
        {
            return false;
        }

        return _prose.TryEnqueue(new DigestProseJob(userId, localDate, sourceHash, locale, now, pool));
    }

    /// <summary>
    /// Rebuild the response from a stored row. EXPLICIT rather than returned by
    /// reference, so a field added to the schema without a migration surfaces here
    /// instead of silently missing from the response — and so a caller cannot mutate
    /// the cached instance.
    /// </summary>
    private static DailyDigestPayloadDocument FromCache(DailyDigestPayloadDocument payload) => new()
    {
        LocalDate = payload.LocalDate,
        GeneratedAt = payload.GeneratedAt,
        Headline = payload.Headline,
        Counts = new DailyDigestCountsDocument
        {
            DueToday = payload.Counts.DueToday,
            CompletedToday = payload.Counts.CompletedToday,
            OpenTotal = payload.Counts.OpenTotal,
            Slipping = payload.Counts.Slipping,
            NeedsInput = payload.Counts.NeedsInput,
            ScansAwaitingReview = payload.Counts.ScansAwaitingReview,
        },
        EstimatedMinutesToday = new DailyDigestEstimateDocument
        {
            Min = payload.EstimatedMinutesToday.Min,
            Max = payload.EstimatedMinutesToday.Max,
        },
        Themes = payload.Themes
            .Select(t => new DailyDigestThemeDocument
            {
                Label = t.Label,
                Count = t.Count,
                TaskIds = t.TaskIds.ToList(),
            })
            .ToList(),
        BusiestDay = payload.BusiestDay is null
            ? null
            : new DailyDigestBusiestDayDocument
            {
                Date = payload.BusiestDay.Date,
                Count = payload.BusiestDay.Count,
            },
        Duplicates = payload.Duplicates
            .Select(d => new DailyDigestDuplicateDocument
            {
                Title = d.Title,
                Count = d.Count,
                TaskIds = d.TaskIds.ToList(),
            })
            .ToList(),
    };
}
